export { default as Hero } from "./Hero";
export { default as About } from "./About";
export { default as Stats } from "./Stats";
export { default as Services } from "./Services";
export { default as TechStack } from "./TechStack";
export { default as Education } from "./Education";
export { default as Portfolio } from "./Portfolio";
export { default as Gallery } from "./Gallery";
export { default as Contact } from "./Contact";
